### ISSUE TITLE
Add the label "Logo" to links property in Community Schema.

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#106]
For the visual aspects of OpenEbench it would be interesting to add a label "Logo" to the links property which accepts an Uri as a value in the Community Schema.

**Comment by jmfernandez** [comment]
Now links are generalized in Community since c36daaca4e5b4b7c5cfc53a0ecb1cf0195320b75 , and `Icon` links are supported since dc32b3c8974aadbe89ed213c3b4d655bd63ba084 , this issue should be fulfilled
