### ISSUE TITLE
Challenge schema

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#107]
In the new [metrics_categories](https://github.com/inab/benchmarking-data-model/blob/1.0.x/json-schemas/1.0.x/challenge.json#L112) property within the challenge schema, shouldn't we have a 'required' attribute specifying that (at least) metrics is compulsory in that object?

**Comment by jlgelpi** [comment]
Also, input datasets, etc.  Howeve, I would wait to put this explicitly in the schema until we have some complete data to check the details.

**Comment by jmfernandez** [comment]
From a fast exploration in the current database entries, I have seen all of them are using the declaration of `metrics_categories`. So, it is being required in new 2.0 data model since 8b5a081968842771d1ec7fabd594352fa9f0a663 commit.
