### ISSUE TITLE
Reference schema '_id'

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#109]
The current json schema for references uses this regex for _id validation:
`"pattern": "^doi:[0-9]{2}\\.[0-9]{4}/"`
 which does no allow to validate all kind of DOIs.
I came across this f1000research paper 

> doi:10.12688/f1000research.7118.2.

Should we use the following pattern instead¿?
`"pattern": "^doi:[0-9]{2}\\.[0-9]{4,}/"`

**Comment by jmfernandez** [comment]
Yes, you are right:

https://en.wikipedia.org/wiki/Digital_object_identifier#Nomenclature_and_syntax

**Comment by jmfernandez** [comment]
Fixed at https://github.com/inab/benchmarking-data-model/commit/ed1f5fb8f0c6ad7c85d02346eff3370bcad02b73
