### ISSUE TITLE
"tool_access" in "Tool"

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#11]
The tool could be a method or an algorithm, so the related link could not be an access point but a link to the source code or to a paper containing the algorithm.
In the case of REST services, it probably should be better to provide a link to the instructions on how to build the URLs to make queries instead of the base URL which is not a valid link per se. 
Proposed solution: to specify the type of link (documentation, source code, REST API, WSDL, etc.)

**Comment by jlgelpi** [comment]
Agree in general, but the link we need is the one that matters for benchmarking, ideally one that allow to execute the tool on a given input dataset.
