### ISSUE TITLE
Community schema '_id'

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#110]
If an external user (community manager) wants to upload the full dataset for his community to Level 1, he should be able to set the community ID he pleases, and then we are the ones who set the official OEB id.

Currently, this is not possible with our data model, as the [community schema](https://github.com/inab/benchmarking-data-model/blob/master/json-schemas/1.0.x/community.json) has an '^OEB...' constraint for the ID. Shouldn't we have a OneOf option for an 'open' ID, like he rest of the schemas¿?

**Comment by jmfernandez** [comment]
This issue should be (hopefully was) managed at https://gitlab.bsc.es/inb/elixir/openebench/openebench-rest-api (CC @redmitry ), so closing this issue
