### ISSUE TITLE
Metrics labels

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#111]
Add new property to metrics schema, which would correspond to a string 'label' that we will be used to name the plot axis. 
Then the current 'name' property would correspond to the default name set by the workflow.

To map the data coming from the workflow with the metrics stored in the database, we could use that 'name' or the 'OEB id' (if available).

**Comment by jlgelpi** [comment]
Consider to add a more complex object to define all axis details: label, units, axis tics, etc.

**Comment by jmfernandez** [comment]
Metrics schema, as all the other concepts modelled by the benchmarking data model, gained a `_metadata` key, which was initially designed to hold OpenEBench platform information like "validated with some validator", "validated with an specific GitHub checkout of the data model", "signed by ...", etc... It can also be used to hold these labels, or other information tied to the representation
