### ISSUE TITLE
TestAction types: AggregationEvent vs. StatisticEvent

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#112]
Should we keep both of them? For now we are only using AggregationEvent, as in the process of merging several assessment datasets into a single aggregation dataset.
StatisticEvent was inherited from v0.4, I remember we decided to keep it for specific 'statistical' processes but not sure if it is worth to keep it anymore.

**Comment by jlgelpi** [comment]
I would prefer not having different object for the same kind of contents. We do not handle inheritance, but clearly StatistictEvent looks like an especialized type of Aggregation
