### ISSUE TITLE
TestAction "_metadata" vs "metadata" properties

### ISSUE THREAD

**Issue by redmitry** [inab/benchmarking-data-model#113]
Hello,

There are two metadata properties in the TestAction. Is this supposed?

Cheers,

D.

**Comment by jmfernandez** [comment]
If you read the description of them, they have very different purposes. `_metadata` is generic to almos all the entries, and `metadata` is specific to TestAction. But it is true their very similar names can mislead the people.

So, the most specific one should either disappear or be renamed. What do you think @javi-gv94 @jlgelpi @scapella ?

**Comment by javi-gv94** [comment]
if we had a clear purpose for "metadata", we should rename it. But I think it is not the case - we haven't used it so far, so I suggest to remove it an move its content  (Relevant metadata used to call the tool) to "_metadata".

**Comment by jlgelpi** [comment]
+1

**Comment by jmfernandez** [comment]
Removed `metadata` from `TestAction` in c4b3808bb4be8bb3ed6416ab4cc9eab4ce70f298
