### ISSUE TITLE
Contacts should include the community_roles

### ISSUE THREAD

**Issue by redmitry** [inab/benchmarking-data-model#115]
Hello,

We need to distinguish OpenEBench community users by their roles (and thus permissions) to manage the data.
~~~json
"community_roles": {
    "title": "Community roles applied to the contact",
    "type": "array",
    "items": {
        "type": "string",
        "enum":  [ "admin", "???" ]
}
~~~

Note that we already have the "contact_type", but the purpose is different.
Q. How compatible they could be? 
Example: "contact_type": "helpdesk", "community_roles": ["admin"]

Your opinions are welcome.

D.

**Comment by javi-gv94** [comment]
Nice! My suggestion for the roles would be: admin (us), manager, developer, other

**Comment by redmitry** [comment]
lo unico que es mejor prefijar "community_admin", "community_manager"... porque esos roles van a ser roles de KC y KC tiene un role "admin" por defecto. Que os parece?

**Comment by javi-gv94** [comment]
what would be the difference between  "community_admin", "community_manager" then?

**Comment by redmitry** [comment]
... good point. "openebench_admin"?

**Comment by jmfernandez** [comment]
Question to @redmitry , are roles managed by server side code based on (hidden) entries of https://github.com/inab/benchmarking-data-model/blob/2.0.x/json-schemas/2.0.x/admin/privilege.json ?

**Comment by jmfernandez** [comment]
Is this issue related to issue #79 @redmitry ?

**Comment by redmitry** [comment]
IMO this issue is deprecated.
We have Privilege collection where all roles are defined
