### ISSUE TITLE
Datasets should have version provisioning

### ISSUE THREAD

**Issue by jmfernandez** [inab/benchmarking-data-model#118]
As datasets can evolve, having different DOIs whenever it changes, its history should be kept in some way

**Comment by jlgelpi** [comment]
Additional question: Can be two (o more) versions of the dataset be active at a given time?

**Comment by jmfernandez** [comment]
So, we should try finding an scenario were two or more versions of a dataset are actively used within OpenEBench

**Comment by jmfernandez** [comment]
Data model is going to be 'uplifted', so definitive identifiers could contain the revision number. The `version` field will be then obsolete.

**Comment by jmfernandez** [comment]
Maybe `version` should be renamed to orig_version, in case it is useful for the communities

**Comment by jmfernandez** [comment]
At the end, server side should manage revisioning (it is published through `@revision` on API request), and understand canonical identifiers. But as not all the concepts have OpenEBench generated identifiers, only these last ones should have the revision in the `@canonical_id` of their entries.

Now https://gitlab.bsc.es/inb/elixir/openebench/openebench-rest-api and related programs should implement the management support for both `@revision` and `@canonical_id`, as they were declared in commit fd535ab4ea99e63ec1158022761294493b7500ec
