### ISSUE TITLE
Add "Participation Model" to Benchmarking Event

### ISSUE THREAD

**Issue by lcodo** [inab/benchmarking-data-model#126]
Specify the way participant can join to a Benchmarking Event. Options could be:

- "Under Approval" _(default)_: data submission to these events is open to all Participant Tools, as long as the submitter is granted a "contributor" role. The petition requires to be approved by the event manager/s. _Submission model Implemented_
- "Open":  data submission to these events is open to all Participant Tools, as long as the submitter is granted a "contributor" role. No approval is required. _Submission model NOT Implemented_
- "Closed": data submission to these events is restricted to set of Participant Tools selected by the event manager/s. _Submission model NOT Implemented_

Alternatively, we can capture in this property the anonymity requirements of the Participant Tools, i.e., "Under Approval with Identified Participant Tools", "Open with anonymous Tools", etc.

**Comment by jmfernandez** [comment]
Closed at commit bc48fa7fcba84835b36320a96976135d68220311 (please have a look both at the commit description and the schemas)
