### ISSUE TITLE
Include keywords for scientific community, benchmarking events and challenge

### ISSUE THREAD

**Issue by scapella** [inab/benchmarking-data-model#128]
Add an attribute to capture keywords (1 or more) for describing a scientific community, benchmarking events and challenges. This would facilitate findability of information in OpenEBench. Keywords can be either free text or part of an ontology.

**Comment by jmfernandez** [comment]
Depending on whether you want to enforce some kind of validation, or only a simple "free keywords space", it can be either improved or left as it has been set at commit b3324892246b0545257d62b91ef105c5cbc56f1c
