### ISSUE TITLE
Should _`email`_ be a required key in `Contacts`?

### ISSUE THREAD

**Issue by jmfernandez** [inab/benchmarking-data-model#130]
`Contact` entries are supposed to be there for attribution purposes. So, there could be some cases where who has prepared the entry does not know a valid e-mail address of the `Contact`. Even worse, there could be some corner cases, like people leaving science or deceased researchers where the e-mail is either unknown or not meaningful.

**Comment by jlgelpi** [comment]
The concept of "contact" implies that shoud be a way to actually contact him/her. Retired/deceased people cannot "contacts" for communities or tools. They can be "authors" or contributors but never contacts

**Comment by jmfernandez** [comment]
Comment https://github.com/inab/benchmarking-data-model/issues/129#issuecomment-1178871829 is related to this issue. The whole benchmarking data model should be analyzed, so all the relations to `Contact` are truly to contacts or they should be pointing to a new `Contributor` concept.

**Comment by jmfernandez** [comment]
Conclusion: Contact entries always have an ORCID, either real (for real people) or a fake ORCID (computed from e-mail address using sha256-48, integrating it in an ISNI starting with 9). So, a new restriction is that Contact has a single e-mail address instead of a list of them.

**Comment by jmfernandez** [comment]
> Comment [#129 (comment)](https://github.com/inab/benchmarking-data-model/issues/129#issuecomment-1178871829) is related to this issue. The whole benchmarking data model should be analyzed, so all the relations to `Contact` are truly to contacts or they should be pointing to a new `Contributor` concept.

So, if we want to restrict the relationships to real people (aka Contributor), all the foreign keys should also include a restriction about the ORCID, like `"pattern": "^orcid:0"`
