### ISSUE TITLE
Allow Dataset with no rel_dataset_ids

### ISSUE THREAD

**Issue by redmitry** [inab/benchmarking-data-model#138]
For the "participant" datasets there are situation when the Participant (tool) has no inputs (simulations, synthetic data generatiors, etc).
This way the dataset must be able to have the dependence on the tool only.
Current JsonSchema disallows this:
https://github.com/inab/benchmarking-data-model/blob/0c92a927d3367dffea1a238aadd2d71c85848b40/json-schemas/1.0.x/dataset.json#L225

we need either make rel_dataset_ids optional or IMHO better remove minItems: 1 restriction (which is more explicit).

**Comment by jmfernandez** [comment]
@redmitry could you check whether change at 2786fbd6febaac5b050f1b1b5a4be3dbb352f195 could cope with the use case, please?

**Comment by jmfernandez** [comment]
As no feedback was received in these months, I consider the use case is properly covered
