### ISSUE TITLE
Add submission capabilities to reference validation programs

### ISSUE THREAD

**Issue by jmfernandez** [inab/benchmarking-data-model#16]
As benchmarking API is approaching the beta state, sooner than later people from the different benchmarking communities are going to need an easy way to submit their data sets.

A natural place where to do it are the reference validation programs, once they learn how to reach each one of the endpoints based on the kind of document to be uploaded

**Comment by jmfernandez** [comment]
This issue depends on #15

**Comment by diglesia** [comment]
The person in charge of checking the content should be a member of the community. Anyone sending data to the benchmarking platform should be in the contacts list.
Maybe, each piece of data that is uploaded to openEBench should have an "owner". There could be two different roles: data "uploader" and supervisor. Every piece of data should be linked to its owner.

**Comment by JuergenHaasSIB** [comment]
uploader is like a depositor, where e.g. in the case of ModelArchive.org a PhD student or PostDoc would upload the data. owner should be always the PI. His identity and email is less likely to change and in particular easier to retrack as long as they stay in academia.

**Comment by JuergenHaasSIB** [comment]
+1 for owner

**Comment by jmfernandez** [comment]
For the moment, it is being handled by the contact ids and the context. It is related to the credentials used to put these entries in the registry. Eventually, we should distinguish between depositor of the record and owner of the data.

**Comment by jmfernandez** [comment]
Transferred to #79
