### ISSUE TITLE
Add visibility labels

### ISSUE THREAD

**Issue by scapella** [inab/benchmarking-data-model#17]
Participants and/or organizers should be able to establish the level of visibility for their contributions.

We can discuss how to properly implement this but I'm thinking something like this for participants:
1. Private: Participants' submission will be always private to the participants.
2. Public: Participants' submission will become public once all metrics become available.
3. Challenge-only: Participants' submission will be available/visible to other participants in that challenge. Once the challenge is over this should be move automatically to public.

For organizers - I don't think challenge should be private.
1. Challenge-only: Data would be visible only for participants.
2. Public: Data will become available as soon as it is ready.

**Comment by diglesia** [comment]
Agree. I think this information should be placed in the testEvent. Anyway, with regards to the "Challenge-only" visibility, is it really necessary? Could you give an example please?

**Comment by jmfernandez** [comment]
We should also take into account the embargo/visibility of the data related to the testEvent

**Comment by jmfernandez** [comment]
Added "public" to the "dates" block, so it can be setup when a benchmarkingEvent, a testEvent or a dataset can be shown (commit 23c311e7aa4a5c985575dd3ebbf1e8ff83cca153)
