### ISSUE TITLE
Multiple submissions by same participant/resource

### ISSUE THREAD

**Issue by scapella** [inab/benchmarking-data-model#18]
Thinking about the data model, it is not clear to me that a given participant for the same tool and a different configuration can take part of the same challenge.

@jlgelpi @jmfernandez could you clarify, please?

**Comment by jlgelpi** [comment]
Same tool and different configuration should generate a new TestEvent. A participant can generate as many TestEvents as necessary. Just to make sure that execution metadata is included in the model.

**Comment by diglesia** [comment]
Please, could you define "configuration"? Does it depend just on the input/reference data provided to the tool or does it also refer to the execution conditions (for technical benchmarking)?
- In the first case, whether we generate a new TestEvent for each configuration of the same tool we should define its identifier accordingly to be able to distinguish among them (I think we haven't defined a formal/standard identifier for the testEvent yet). 
- In the second case, we have already discussed about using containers to provide participant tools with a common execution environment under the same conditions. If the conditions change, they would change for all participants so I think it should be considered as another benchmarkingEvent

**Comment by jlgelpi** [comment]
It should be any specific metadata that allows to distinguish two executions from each other: Input/reference datasets, parameters used, execution environment, or simply several independent replicas (that may have some meaning depending on the tool). The way to specificy this is tool dependent. 
Conditions that are common to all participants should not be placed in TestEvent, rather in BenchMarkingEvent. 
Currently TestEvent ids are set by the data provider, the only condition is that should be unique.

**Comment by diglesia** [comment]
We should include a field in testEvent to define the setting parameters/configuration. Conditions that are common to all participants should not be placed in TestEvent, but in BenchMarkingEvent.

**Comment by jmfernandez** [comment]
There are two different issues described here:
- The need to link the specific execution conditions (which can be done since commit 572a7addf0f92c4a50d354db644197011b729972 )
- The need to uniquely identify different participants where the same contacts and tool are used (commits 6f7a0ce4a5c7fdf2be5e1c2d99b70e4a8c31c1a1 and d119180410da087b92ffc758e6c86e86a7183d3c ).

Hopefully, both of them are now fixed
