### ISSUE TITLE
Contact's _id

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#2]
Use of givenName.surname as _id is potentially ambigous. We need a way to solve repeated names.

**Comment by jmfernandez** [comment]
A possible way could be using as _id something like the UUID of givenName+surname+creation date, so two users with the same name do not collide

**Comment by jlgelpi** [comment]
More general:   community_:prefix:givenName.surname ?

**Comment by diglesia** [comment]
Agreed proposal: we will request contacts to have an ORCID account and use the ORCID as identifier.
