### ISSUE TITLE
Tool's status modification Date

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#20]
Date of the last modified status. Useful when tool is down or obsolete

**Comment by diglesia** [comment]
Agreed: We should include in toolStatus a new field: Tool's status modification date.

**Comment by jmfernandez** [comment]
Committed d35878d47613768e997ee9da9fcc6953cdbf5d2f . Should we include an additional field, like a keyword or an acronym, which helps classifying the status modification?

**Comment by diglesia** [comment]
I think that having the date and the current status would be enough for the moment. We can check whether we need additional info for v0.4.x
