### ISSUE TITLE
Tool's version

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#21]
For obvious reasons

**Comment by jmfernandez** [comment]
I also agree. How should we handle this? More in the non technical way (with a version string) or the more technical one (referenced to bioTools, bioconda, github, etc...)? Or both?

**Comment by jlgelpi** [comment]
In any case, version is a well known metadata en benchmarking. A string could be enough, but a github reference sould be better when available.

**Comment by diglesia** [comment]
I would keep it simple by using a version string, letting the discussion on the technical approach for future versions

**Comment by diglesia** [comment]
We will include a version string in v0.3.x.
For v0.4.x, we can also include a github reference (when available)

**Comment by jlgelpi** [comment]
Included in #32
