### ISSUE TITLE
Community prefix in Tool

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#25]
A tool could participate in several communities/challenges so its ID should be declared without the community prefix. However, this could lead to a duplication of tools. For instance, in CAMEO, some tools are called Server<number> instead of using their actual name, so we will not be able to distinguish them.

**Comment by jlgelpi** [comment]
I would keep them prefixed until we have a real example of this. We could add a property pointing to alternative ids. Also if we remove the prefix we should move community_id to an array.
