### ISSUE TITLE
dataset_contact_id in Dataset

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#27]
dataset_contact_id is a required field for defining datasets, but it could be difficult to find this information in some cases. Is it necessary? Should we provide the community contact when the dataset contact is not available?

**Comment by jmfernandez** [comment]
For reference datasets it should not be required

**Comment by jmfernandez** [comment]
I agree with adding the community id

**Comment by jmfernandez** [comment]
The contact_id can be understood either like the depositor of this link or the real owner of the data. I think it should be the former . I'm leaving this issue open

**Comment by scapella** [comment]
It must appear, due GDPR issues

**Comment by jmfernandez** [comment]
Closed with a clarification that this contacts correspond to the depositor or creator, at 2a98febd1e7ff66605045544eed6ba35494be11d
