### ISSUE TITLE
toolStatus and toolAccessType

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#28]
toolStatus and toolAccessType will be frequently accessed so it could be better to include them as fields within Tool.
Proposal:
- toolStatus could be transformed into an Enum field within Tool. Values could be: active/inactive (for tools), implemented (for algorithms), unknown, etc.
- toolAccessType could also be transformed into an Enum field within Tool. Values could be: SOAP API, REST API, algorithm implementation, VM, etc.

**Comment by jmfernandez** [comment]
I agree with you. We should agree in advance a life cycle of a versioned tool, with the specific states of remote ones, like web services

**Comment by jlgelpi** [comment]
Decision: Move those type of data to Json Schema as enum

**Comment by JuergenHaasSIB** [comment]
+1

**Comment by jmfernandez** [comment]
Fixed at 78ff9eebf45f706a7796d0baa44e8d65edbd44a0 and 5fa7ffd564619e85f4894d779cc534a87a21948a
