### ISSUE TITLE
execution_type in Metrics

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#29]
Possible values for execution_type should be defined (Enum) to avoid confusions

**Comment by jmfernandez** [comment]
Or we should use a anyOf construction, which is going to be refined with the different needs we have. At the beginning we can put what it is needed for metrics in dockers

**Comment by jmfernandez** [comment]
As Metrics has an implementations section since d66f4252107d9e36517c11c4b049cea9de3119a7 , it was also removed then the `execution_type` attribute (it depends on the implementation)
