### ISSUE TITLE
Contacts givenName, surname

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#3]
Why should be arrays?

**Comment by jmfernandez** [comment]
They are arrays in order to hold middle names, or people from countries with several surnames

**Comment by jlgelpi** [comment]
Do not know. This make sense to search "Jose" and "Jose Maria" as separate options, but probably end up you being found looking for "Maria" :-). I would rather use simple strings (including middle names, and any list of surnames), open to discussion any way

**Comment by jlgelpi** [comment]
Data in Repository is inserted as strings in teh present version

**Comment by jmfernandez** [comment]
In progress

**Comment by jmfernandez** [comment]
Fixed on commit 0cbdab0f010d8948e1752b7dedcc656720dad1b1
