### ISSUE TITLE
Tool data model to be revised

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#32]
Whitin the Biocontainers Implementation Study, we will receive a series of data and metadata from tools that may not be at bio.tools. This should go to Tools Monitoring  but it is probably necessary to move the Tools at openEBench to a more abstract level so, could be used in both platforms and show more information from the tool itself (this is not a bio.tools alternative but it is getting close).

**Comment by jmfernandez** [comment]
I have been looking for a namespace for biocontainers in identifiers.org, but it is not available. The same happens to Galaxy and Bioconda . The only available namespace which can be used is biotools.

So, should we encourage the different communities the registration of bioconda, biocontainers and / or galaxy workflows namespaces in identifiers.org?

**Comment by jlgelpi** [comment]
I think Biocontainers should be in, as it is going to be "Elixir" infrastructure. Not sure about the others. In the mean time we (should) have the information to do the resolution.

**Comment by jmfernandez** [comment]
I have just researched a bit, and anyone can request the creation of an identifier prefix in identifiers.org . Should we ask for it?

**Comment by JuergenHaasSIB** [comment]
I think it makes sense if you actually have an identifier like the PDB 4AKE and then can link to it...
or a CAMEO ID 2018-07-07_00000000_1 (https://www.cameo3d.org/sp/targets/target/2018-07-07_00000000_1/)
We actually have the bio.tools ID or better: our own IDs?
I vote for yes

**Comment by jlgelpi** [comment]
Waiting to the final decission on "Tools ecosystem" identifiers

**Comment by jmfernandez** [comment]
Any news?

**Comment by jlgelpi** [comment]
Nothing new afak
