### ISSUE TITLE
Empty properties

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#35]
We should decide whether empty properties (obviously not required) should be 1) present and empty (the SQL classical approach), or 2) simply absent (more noSQL). 
1: Better organization of data, however more difficult to check (in mongodb it is easier to check por the presence of a field, than for an empty value that can differ on each data type), uglier json reports.
2: Easy to check field presence on db, simpler Json outputs, especially for flexible schemas.

**Comment by jmfernandez** [comment]
This is a databases theory philosophical question ;-) related to optional and / or unknown values . Relational databases did not have optional columns, so the solution was to create the NULL value. In the JSON + JSON schema world, as you have pointed out, is richer.

- When there is an empty property (i.e. a property which admits a **null** as a valid value), we know we do not know its value, but we know the program or person which/who generated the JSON document knew about the property existence.
- When an optional property which does not admit a **null** does not appear in a JSON document, it can mean either its generator did not have a value for it, or the generator did not know about this property. This latter could happen when an outdated JSON documents generator still generates content.

So, IMHO we should discourage the admission and usage of **null**, as it can also be used to catch programming flaws in the different benchmarking JSON data generators. In some programming languages and libraries, when a JSON data serialization fails for custom instances, it either fails or is usually replaced by a **null**.

**Comment by scapella** [comment]
No invented field should be allowed

**Comment by JuergenHaasSIB** [comment]
I would like to have them filled, ie SQl style, more like verified and set to empty.

Empty properties can be e.g. oligomeric scores that are empty, because the prediction is always a monomer. same for ligand pose scores, if the server does not include ligands.
This is related to the discussion of how to convey metrics to the end-user.
a person looking to embark for ligand modeling surely would like to get those servers that show the scores.

**Comment by JuergenHaasSIB** [comment]
might be overdoing it in any case. 
just wanted to differentiate between a method not being able to score and the assessment failed to produce score.
I would even leave it and close issue.
