### ISSUE TITLE
datalink from dataset.json improvements

### ISSUE THREAD

**Issue by jmfernandez** [inab/benchmarking-data-model#36]
"datalink" from dataset.json currently holds a single link, which is ambiguous, as it could be a directory.
The ways to improve it are:

- Each link references a single file/archive.
- Allow referencing more than one file.
- Store the MD5/SHA1/.... checksum of the referenced resource

**Comment by scapella** [comment]
Include validation of the URL

**Comment by jmfernandez** [comment]
Fixed at 36856373f0c56f74f7be431f89ef1095c8e0a024 and f6db686bf8b278a83a54c0bb6db8c3eaac471aa6
