### ISSUE TITLE
Participant in TestEvent

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#38]
We have the contact info for the responsibles of the challenge in BenchmarkingEvent but we need to know who is participating in each specific TestEvent. So we should add contact info to TestEvent

**Comment by jlgelpi** [comment]
+1, As I remember the contact type was open to any type of person, but the link in testEvent was not there

**Comment by jmfernandez** [comment]
Fixed with 1c6121e4e8318ceb0d47618bc212ae978f7e81e3 and 1eece57e946a1171f7d27e47980a3f858daa2caa commits. The participants of a `benchmarkingEvent` appear in it, and the `testEvent` now also can contain the same information
