### ISSUE TITLE
Publication type in Reference

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#39]
We should distinguish the publication type: primary, review, update, etc.

**Comment by diglesia** [comment]
We should consider to include the publication type in Tool instead of Reference

**Comment by JuergenHaasSIB** [comment]
Let's include the reference in the metrics or tool and stop entering pubmed data that we can easily get programmtically on the fly - we should store no more than DOI or PUBMED ID.

**Comment by jmfernandez** [comment]
I have cleaned up a bit `Reference`, removing `links` property from it (commit 9e51942e3c42c261af01beae41fbbf3694d13c19)
