### ISSUE TITLE
metrics in Dataset

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#4]
Dataset should refer to the data irrespective of how we use it. 
datasets can be used in more than one testEvent, so putting results of metrics there could be very complicated. 
I think that results (datasets+metrics applied) should be considered additional datasets.

**Comment by jmfernandez** [comment]
Yes, that's what I was thinking about when I designed it. The output dataset can point to the same raw data as the input one, with the metrics labelling it.

**Comment by jlgelpi** [comment]
It is complex, we need to store also the raw output datasets generated by the tools or uploaded by participants. 
So I see several types:
"Input": Basically static and probably used in more than one BenchEvent
"Output": Contributions to the Benchmarking event (linked to a TestEvent: inputDs + Tool->outputDs)
"BenchResults": Here we have several options: 
a) Results per tool: For all OutputDS(Input) + Metric -> ResultsSet (Same input, and metric applied to outputs of several tools. This is the CAMEO example)
b) Results per metric: OutputDS + All appropriate metrics ->ResultsSet (Same Output, but several metrics applied).
If we store results as just [OutputDS, metric]-> value we could recover them either way.

**Comment by diglesia** [comment]
Open discussion for version 0.4.x. Input and output datasets could be just a reference/URL to the actual datasets. We should further discuss how can we represent the results (metrics, summary/report, aggregated results, etc)

**Comment by jmfernandez** [comment]
@diglesia and @jmfernandez have been talking about unifying input_dataset_id and output_dataset_id as dataset_ids with the roles they have played in this testEvent: Input, Output and BenchResults. testEvents always have to reference either declared input datasets from benchmarkingEvent (as a participant) or one or more previously labelled output datasets from other testEvents (as an evaluator)

**Comment by jmfernandez** [comment]
We have to unlink metrics results from datasets, as metrics already are datasets. But the metrics datasets should have a testEvent id instead of a contact id

**Comment by jmfernandez** [comment]
Done in 93a09ff3f9f5e7e6ada9c03e730aec05ccf70578 in a different way
