### ISSUE TITLE
Metrics in BenchmarkingEvent

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#41]
Each BenchmarkingEvent should include a reference to its Metrics (missing in the current data model)

**Comment by jlgelpi** [comment]
However, metrics do reference the Benchmarking Events, I use that in the API, perhaps we do not need to make all the links, just to make sure that the link exist

**Comment by jmfernandez** [comment]
Are you sure? I guess it happens in your denormalized data model, but not in this

**Comment by jlgelpi** [comment]
may be, I'll check, in any case I think that it is easier to link events from their components to the Event not the opposite, to avoid having a long list of keys in the BenchEvent  (i.e. lnks to metrics, to testevents, to datasets ...)

**Comment by jmfernandez** [comment]
Fixed in commit 1c6121e4e8318ceb0d47618bc212ae978f7e81e3
