### ISSUE TITLE
Mention CURIEs authoritative entity in the whole schema and documentation

### ISSUE THREAD

**Issue by jmfernandez** [inab/benchmarking-data-model#42]
As we are officially adopting CURIEs, and we are using identifiers.org as the authoritative source of those prefixes used in the CURIEs, we should clearly document it

**Comment by jlgelpi** [comment]
We should use identifiers.org, however they will not have all the namespaces we need. For instance, tool names in CAMEO are specific. We will keep a resolver service .../idsolv integrated in openEBench.

**Comment by jmfernandez** [comment]
I have been reworking idSolv a bit (commit 1cef6222a971d87610abfceaebcbad093bb3a624). Needs to integrate it tighter into the benchmarking schema
