### ISSUE TITLE
Should Tool and Metrics become one?

### ISSUE THREAD

**Issue by jmfernandez** [inab/benchmarking-data-model#44]
With the current changes (as of 1eece57e946a1171f7d27e47980a3f858daa2caa), there is no specific dependency on `Metrics`. We can either include a reference to `Metrics` in `Dataset`, or we can replace the reference of `Tool` by `Metrics` in `metrics_tool_id` attribute from `BenchmarkingEvent`, if we want to keep `Tool` and `Metrics` separated

**Comment by jlgelpi** [comment]
Decision: Consider metrics as standard tools:
- Use "role" in Tool's schema to indicate "metrics"
- Adapt "data_schemes" for eventual need of execution. Perhaps use "EDAM-like" as in the tool. 
- Pending: Recover "Formal definition" for metrics
