### ISSUE TITLE
Define order of upload for json components, to avoid issues on server validation

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#45]
Validation on server is done in order of receipt

**Comment by jlgelpi** [comment]
Can be obtained from the schema

**Comment by redmitry** [comment]
For the batch upload via POST it is possible to send objects in arbitrary order.
The implementation streams objects into the mongodb.
It retains objects with broken FKs in a hope to find the referenced object later.
Once the stream is over, it pushes objects in a correct way.
If not all objects where successfully pushed, validation errors are returned, so the client can extract the IDs of failed objects.

**Comment by redmitry** [comment]
This is not the data model issue, but benchmarking  API one.
