### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#5]
Possibly, to be more open, doi, pubmed_id,etc. could be reformulated as:

```json
"bibliografic_ids" : {
   "type": "array",
   "items" : {
      "type": "object",
      "properties":  {
            "source" : {
                 "type": "string",
                 "enum": ["doi","pubmed_id","...."]
            },
            "uri": {
               "type": "string",
             }
      }
 }
```

**Comment by jmfernandez** [comment]
Yes, I agree with you

**Comment by diglesia** [comment]
I also agree. We will reformulate it as proposed for the next version of the data model (v0.4)

**Comment by diglesia** [comment]
By default, the reference will be a DOI. If there is any prefix, then we will resolve the URL.

**Comment by jmfernandez** [comment]
Should we use CURIEs?

**Comment by jlgelpi** [comment]
If we use CURIEs there no need to indicate the sources

**Comment by jmfernandez** [comment]
Done in cbfd71a64fc0d80c70fc47d74b47f6b9d0095f91 and 0f5527fef387b1f4e87488b6a919738b6bc3f698
