### ISSUE TITLE
Dataset model: Need a version of "datalink" for raw scores, perhaps renamed to score or data

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#55]
Proposal:
 "data": {
"score":"62.05", 
"attrs":"raw_score", 
"status":"ok",
"validation_date":"2017-01-18T00:00:00Z"
},

**Comment by jmfernandez** [comment]
Closed at e202a02328a4695e62f406d4e754a1dc232f6a97
