### ISSUE TITLE
TestAction model: recover input/output

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#57]
TestAction is focused on TestEvent, should be more general:
Input(s) + operation + Output

Not sure if "received_datasets" is enough, perhaps we need to recover two separated lists.
Data should depend on operation:
Setup: 
TestEvent : tool_id
MetricsEvent : tool_is, metrics_id
StatisticsEvent: metrics_id?

**Comment by jmfernandez** [comment]
Fixed at 9bbefeeb6f72015699d111eb0f499fb55a5224e9
