### ISSUE TITLE
Accessibility models

### ISSUE THREAD

**Issue by scapella** [inab/benchmarking-data-model#60]
Is the four-level accessibility models part of this data model release?
Accessibility models says who has access to what datas in OpenEBench, and can be as follow:

- Private.
- Restricted.
- Community.
- Public

**Comment by jmfernandez** [comment]
As you can see at `Dataset` in 0.4.x branch, the dataset accessibility levels are already modelled at `visibility` key, and the possible values are:

- `public`: visible by everyone.
- `community`: visible by any member of the community.
- `challenge`: visible by any participant in the challenge.
- `participant`: only visible by the submitter.

From the levels you have submitted, `private` would map to `participant`, but I do not know whether `restricted` would map to `challenge`.

We have followed a different approach for TestAction, Challenge or BenchmarkingEvent, as there are there keys which records when the element should be public (so embargoes with deadlines are implemented).

Obviously, all these attributes should be honoured by the APIs
