### ISSUE TITLE
Challenge > datasets/roles

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#62]
In the challenge schema, the available roles for the datasets in that challenge are currently:
_"enum": [ "input", "reference", "metrics", "challenge" ]_

For consistency, I would suggest changing them  to the same as specified in the dataset schema -> types:
_[ "public_reference", "metrics_reference", "input", "participant", "assessment", "challenge", "other" ]_

**Comment by jmfernandez** [comment]
Accepted suggestion at 1ccf8137ca72274a0daf1fbbfcafc8e97eb508de
