### ISSUE TITLE
Minor changes in some schemas to enable validation

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#64]
- **Benchmarking event**: '_is_automated_' is a required property in this schema, however, this attribute is not specified in the properties object.

- **Dataset**: _'datalink_attrs'_ is a required property in this schema; however, this is actually a property called _'attrs'_ within the _'datalink'_ property. Should we remove it from the required properties of the dataset schema?

- **Tool & Community**: this schemas both have a property called _'status'_, but in the required properties array it is specified _'status_id'_. Which one do we want to keep?

-  **idSolv**: currently the property _'_schema'_ in this file is specified as:
         _"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.4/Dataset" ]_
     Should we change it to:
         _"enum": [ "https://www.elixir-europe.org/excelerate/WP2/json-schemas/0.4/idSolv" ]_

**Comment by jmfernandez** [comment]
Thanks for the validation! These are remnants of the previous iterations, which are not caught by the JSON schema validators. I'm applying the proper fixes ASAP

**Comment by jmfernandez** [comment]
Issue was fixed at 326f9507f9050dc99ba5ff04b45ca231c4d2a199 , c0ac71a16dc448173d7f49c53d0c278991e113cd , be75da3efeb962a11d158a1e2bb62c20644562c8 and 5028ff281ce7b6c74fff1a0118e78453030d139f .
