### ISSUE TITLE
One more attribute in Dataset schema

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#67]
In order to facilitate the classification of assessment datasets according to the Challenge they belong to, I would suggest including a new attribute in this schema which points to the corresponding Challenge.
That is useful to build the 'Summary classification' table for a benchmarking event; where we need to retrieve the whole set of assessment datasets, split them, and apply a classification method for each of the challenges.

**Comment by javi-gv94** [comment]
Solved in pull request #71

**Comment by javi-gv94** [comment]
With the new ids this becomes even more important, as we need to query the API and retrieve only the datasets that belong to a certain challenge

**Comment by jlgelpi** [comment]
challenge_id already added to data.
See comment on pull request.

**Comment by javi-gv94** [comment]
Fixed in pull request #78
