### ISSUE TITLE
BenchmarkingEvent: Dates of creation, modification, start, stop

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#7]
Dates of creation, modification, start, stop could not be available for some benchmarking events but they are required fields. For instance, in Quest for Orthologs, such dates are not provided and we can only check the abstract's deadline for the related workshop. This information should be provided by the communities but, in the case of continuous benchmarking, it could be possible that these dates do not exist because the participants can submit the data at any moment, without a fixed deadline. 
Proposed solution:
- To include a condition in the dates-related properties - if there is start date, there should be stop date and vice versa.
- To use the abstract's deadline as stop date.

**Comment by jlgelpi** [comment]
This is a more general problem. Each Community will have specific needs (dates and others). NoSQL allow to use alternative schemas without notice, but in terms of specification this could be a problem. 
Two main options: 
-"Agree" on specific/alternative meanings of the different properties (Easy but less formal)
- Generate inherited classes (just additional schemas, do not know if inheritance is explicit in json schema). This is a more elegant approach, no major problem from the software side, but makes the specification more complex.

**Comment by diglesia** [comment]
We should discuss this in detail but I would choose the first option. The schema could become too complex for the second one. For the first option, we can try to use conditional fields in the schema to represent the specific needs of each community.

**Comment by jmfernandez** [comment]
JSON Schema allows reusing fragments of other schemas (so, common data structures are defined in a single place), but not an OO inheritance (i.e. adding new sibling keys, for instance). Nevertheless, JSON schema also allows defining "free style" (sub)schemas, where you can add additional keys not previously declared in the (sub)schema

**Comment by diglesia** [comment]
Use of alternative schemas: If necessary, we will make use of the JSON schema mechanism that allows defining "free style" (sub)schemas, where we can add additional keys not previously declared in the schema.
