### ISSUE TITLE
Dataset schema: metrics error

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#70]
Some communties (e.g. QfO, CAMEO) consider an error/confidence interval for the metrics apart from the actual value of the metric (stored in the assessment dataset schema), which is an important part of the visualization. How should we keep track of those errors?

- Create a new attribute in the dataset schema to store the metric error value.
- Consider the metric error as a 'new' metric, which would mean adding more testactions and datasets to the data model structure.

**Comment by jmfernandez** [comment]
Could you provide one or two example links to existing entries requiring it, please?

**Comment by javi-gv94** [comment]
Examples from Quest for Orthologs:

- [Error in one  of the metrics](http://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2)
- [Error in both metrics](http://orthology.benchmarkservice.org/cgi-bin/gateway.pl?f=CheckResults&p1=72d29d4aebb02e0d396fcad2)

**Comment by jmfernandez** [comment]
Links are working, but they are showing nothing in a cold load. Could you attach screenshots to the issue, please?

**Comment by javi-gv94** [comment]
Sorry, I was updating the previous post. Here an example for one of the benchmarks in QfO:
![plot_sqr](https://user-images.githubusercontent.com/15807311/49091522-50222f80-f260-11e8-8ccb-7e2130b49fae.png)

**Comment by jmfernandez** [comment]
I guess you are referring to this:

![image](https://user-images.githubusercontent.com/2072150/49092063-14d03280-f259-11e8-97ca-5d9a71788913.png)

In that case, what you can do is storing as metric value a JSON object with two keys, metric value itself and metric value error. Is it feasible?

**Comment by javi-gv94** [comment]
Yes that could be the solution. We can encode both values in the data-uri attribute.

**Comment by jmfernandez** [comment]
Then I'm keeping this issue open until you have tried that approach

**Comment by jmfernandez** [comment]
Applied changes on commit fddca4987b77624732d68e4692b57c1f69c52ac2 which allow having complex, structured inline values
