### ISSUE TITLE
Assessment datasets - link to data

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#73]
While looking again deeply into QfO data I've realized they consider two kind of assessment datasets (and probably this is also extendable to other communities):

- A file where the comparison with the gold standard is done. See [this example](https://orthology.benchmarkservice.org/raw//TreeTest/Eukaryota.1f80d28e8ffd8052ddb8892e.tsv.gz). In this case, it is a comparison between phylogenetic trees and a value of distance. 
- The other is the value of the metric itself (which is derived from the previous file).  See the first line of [this file](https://orthology.benchmarkservice.org/raw/TreeTest.Eukaryota.14df0c6fe80b583b2bf6eaa1_1.tgz)

Currently we are storing that metric value encoded in a data-uri within the datalink attribute. It is also possible to store the link/path to the assessment file, but now we have no way to store both of them at the same time.

Should we extend the datalink attribute, so that instead of a single object, it becomes an array of objects ?
Or create a new dataset type?
Does that make sense?

**Comment by jmfernandez** [comment]
In this case, I would not make the benchmarking data model more complicated. Instead, I suggest you to use a more complex JSON encoded as data-uri.

Alternatively, you could also create a new, separated dataset for the file, with the type "other", and you could make that the metrics dataset depends on the separated dataset with the role of dependency.

**Comment by jlgelpi** [comment]
I think that to be fully consistent with the schema I see 3 options:
1. to "Two" metrics (one the file, the other values), end then two TestActions of metrics that generate two Assessment Datasets. 
2. (probably better) we can generate a 1st assessment the gives the file, and then a StatisticsEvent that extract the values from the file generating a new assessment dataset with values. 
3. if the values can be extracted easily from the file, actually we do not need to store them. The assessment dataset is the file. we can get them on-the-fly (although this would need a specific code, than would be only used for this case)

**Comment by javi-gv94** [comment]
Extracting the values is quite simple (e.g. it is just counting the number of lines or TP in the file, or getting the average value of all entries...). However, I think it is quite important to store that number somewhere, as it is actually the think we value we will visualize.
My suggestion would be having 3 metricsEvents and 3 assessment datasets per participant:

- The first metricsEvent takes the participant dataset and the metrics_reference dataset, performs the 'comparison', and outputs the first assessment dataset (which is the file)
- The two other metricsEvent would take that first assessment dataset and extract the two metrics values (e.g. recall & precision), which would be stored in the other two asssessment files.
- Finally, the statisticEvent would gather all those datasets into the final 'challenge dataset' (this is what we are already doing).

Hope that makes sense, I think it is important to consider that assessment file as probably a lot of communities use it as 'support' to compute the metrics.

**Comment by jmfernandez** [comment]
Fixed on fddca4987b77624732d68e4692b57c1f69c52ac2
