### ISSUE TITLE
AAI management

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#79]
-Authentication data should be linked to contacts, to allow for automatic tagging of documents with "owners", "depositors" , etc. 
-Contacts_ids in several datatypes should add a "role" 
-Users data should be enriched to include Filiations, Supervisors, Community, ...
-Related to permission request for accessing relevant datasets.

**Comment by jmfernandez** [comment]
I'm afraid this is outside the data model project as such, and it relies more on the implementation. An alternative would be enforcing the contacts to have a public, common property, like the contact's ORCID

**Comment by jlgelpi** [comment]
The original idea was to tag each record with ownership so it can be updated by external users. I agree that it is an "infrastructure" need, but the data model should include some way to link users of the infrastructure and data, otherwise we loose control.
Some communities are already requiring restricted access.

**Comment by jlgelpi** [comment]
A specific data model for use management should be designed.

Aims: 

- Keep track of roles like Community Manager, Community Supervisor, Data owner, Data depositor, etc.
- Keep track of ownership of datasets, metrics etc, and authorization privileges
- Connect with authentication procedures to automate data uploading or modification
- ...

**Comment by jmfernandez** [comment]
I guess this issue is being fulfilled by https://github.com/inab/benchmarking-data-model/blob/2.0.x/json-schemas/2.0.x/admin/privilege.json and the current developments led by @redmitry in a different repository, right?

If it is so, I propose to close this issue.

**Comment by redmitry** [comment]
ALL the code is on the BSC GitLab
https://gitlab.bsc.es/inb/elixir/openebench/openebench-rest-api

**Comment by redmitry** [comment]
Need to provide mandatory verified ORCID attribute in Keycloak registration template.
