### ISSUE TITLE
References in "contact" and "tool"

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#8]
Bibliographic references in "contact" do not use the "reference" entity, they are just a link to the DOI within the "links" of the contact.
Is there any reason to have a contact linked to a list of publications? This list could be very large and, in fact, it does not seem to provide any additional information: we already have the tools linked to their relevant publications.
Proposed solution: To remove the "PublicationDOI" in the "links" related to the "contact". To add other types of links, such as the Twitter account.

**Comment by jlgelpi** [comment]
Agree. Perhaps include "other" as option of allow additional links.
