### ISSUE TITLE
Explicit data access consent

### ISSUE THREAD

**Issue by scapella** [inab/benchmarking-data-model#81]
Dear all,

As discussed in previous occasions, it is important to explicitly model the data access consent to sensitive data. Input data used by participants - especially in level 1 & 2 - can be sensitive because 1) belongs to a human being, and 2) belongs to a data set which has not yet been published.

Ideally we should have an interface to handle both cases when users want to access to a sensitive data set, and that agreement to use that data for benchmarking purposes should be capture. I assume we will need to use ELIXIR AAI to ensure users identity.

S

**Comment by jmfernandez** [comment]
Although the schema already has some provision for data embargoes (look for 'public' key in the different schemas), enforcing them and fine grained ACLs should be managed outside the data model

**Comment by jlgelpi** [comment]
Same problem than #79 . We need an AAI data model that links user data and benchrmarking data

**Comment by jlgelpi** [comment]
#79
