### ISSUE TITLE
Reserve " t " for temporary identifiers

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#82]
As we discussed earlier we will be using the letter **" t "** after the community id to specify the temporary_id before it is uploaded to the database.
ex: _OEBX001**t**xxxxxxxxxxxxxxxxxxxxxx
The new regex pattern would be something like:

**^OEBX[0-9]{3}(t.*|[A-Z0-9]{7})$**

This would validate both the ids

**Comment by jlgelpi** [comment]
Any length? or OEB?[0-9]{3}[tA-Z0-9][A-Z0-9]{6}

**Comment by vsundesha** [comment]
Could be anything a url or a string or just one digit after the "t" it wouldn't matter.

**Comment by redmitry** [comment]
{7} siete!  (seven, семь, saat, set) digitos!!! :D

**Comment by jmfernandez** [comment]
Gentlemen, I have just fixed this issue with commit aa7444bf81b52290683fb8cfa72be92f10e116ac , with the updated patterns. Temporal ids must have the first alphanumeric symbol after the community id set to 't', and the other six alphanumeric symbols are as always

**Comment by vsundesha** [comment]
@jmfernandez  @jlgelpi  Don't we need the temporary id to be anything after the **"t"** because the pattern we have implemented restricts the user to have an id of 6 six alphanumeric symbols, if the ids came from a community we would only have to add the prefix OEBX001t+ the id defined by the community.

**Comment by jlgelpi** [comment]
The pattern I see is just accepting a "t" in the first digit and keeps the original length.

**Comment by jmfernandez** [comment]
@vsundesha , as @jlgelpi is telling, the identifier length is kept in this way

**Comment by vsundesha** [comment]
@jmfernandez I understand that, we can discuss this F2F but i don't see why we have to restrict the temporary id to be somthing like OEBX001t000000 when it can be OEBX001t*

**Comment by jlgelpi** [comment]
Temporary ids can be anything, anb probably we do not need 7 digits, it was just to keep a similar pattern. In any case some pattern should be applied, otherwise the data management at the backend is more complicated

**Comment by jlgelpi** [comment]
Dmitry: A simple and controlled way to get temporary ids, i.e  OEB001t+hash of fixed length made from the orig_id
