### ISSUE TITLE
Tool 1.0 community_id is still marked as required. 

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#83]
The field has been removed as a tool may be used by several communities, but it is still listed in required.
However the ids are still linked to a specific community (related to #25  and #32 )

**Comment by jmfernandez** [comment]
I have just fixed the issue in commit 209347a42dc6cf94d8b689a6bb33779383446127 . I have changed the tool identifier pattern, so it does not contain the 3 digits related to the community. If it seems ok for you, I'm closing the issue later

**Comment by jlgelpi** [comment]
Unless we change completely de tool id to match Tools platform repository, I would keep the OEBTXXX pointing to the first community that generated the tool, just to be consistent, in most cases it would be only one. Perhaps we could add a non required array with community_ids.

**Comment by jmfernandez** [comment]
Ok, I'm rolling back the id pattern change in 382a2b5ec9e07c0dfb23bc601a349c1c1c21d856 . Then, I propose to have a "OpenEBench" community in the future, in order to be able inject new tools, keeping this identifiers schema

**Comment by vsundesha** [comment]
> Perhaps we could add a non required array with community_ids.

I agree with having a non required array since I came across a use case where we will need the community_id in the schema to list the tools that are participating in the community.

**Comment by vsundesha** [comment]
I and @javi-gv94 just noticed that community_id field is present in the database but not in the schema.
