### ISSUE TITLE
Tool tool_access_type(_id) mismatch field name and required list

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#84]
Name of the field differs on the schema and the required list

**Comment by vsundesha** [comment]
On the same note I found a couple of inconsistencies between the keys in different schemas
Community schema | community_contacts -> community_contact_ids
Metrics schema | metrics_contact_id -> metrics_contact_ids
Tool schema | tool_contact_id -> tool_contact_ids

idsolv schema | pattern is missing the property "type"

**Comment by jmfernandez** [comment]
@vsundesha, this issue is focused on name mismatches in different parts of a single schema, not about on how a property is being named in different schemas. So, although the issues you are reporting are legit, they are unrelated to this issue. Please, put them in a separate issue.

**Comment by jmfernandez** [comment]
Issue reported by @jlgelpi has been fixed in 7306e393c9e2cfd6678542d8cf79da9523a4b7ac

**Comment by vsundesha** [comment]
It still has to do with inconsistencies in the schema, but anyways i'll open another one !
