### ISSUE TITLE
TestAction required / additional fields

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#85]
Required fields:
-Tool_id is only required for TestEvent_
-Test_contact_ids also required for TestEvents, unclear in other cases

Additional fields.
Metric_id for MetricsEvent, Assessment

Perhaps all of them should be put on metadata

**Comment by javi-gv94** [comment]
I agree that contact_ids are only required for TestEvent (the person who ran the tool). The rest of the testActions may be done automatically.
But why tool_id only for TestEvent? I think all test actions are associated to a tool

We already have metric_id in v.0.4 data (not required though, as it is only used in MetricsEvent)

**Comment by jlgelpi** [comment]
Well, yes tool_id could be inherited from the previous workflow in assessments, but not in setup for instance. Besides if it is a StatisticEvent aggregating results of several tools than tool_id should become an array. The scenario can be complex. We could make the model more precise consideting those cases.

**Comment by jmfernandez** [comment]
TestAction needs some complicated restructuring (allOf + oneOf combinations) in order to have the required attributes only in some cases.

**Comment by jlgelpi** [comment]
Decision: Keep an open model (use AdditionalProperties as needed)  until more precise cases are available.
