### ISSUE TITLE
Inconsistencies between the keys in different schemas

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#86]
Community schema | community_contacts -> community_contact_ids
Metrics schema | metrics_contact_id -> metrics_contact_ids
Tool schema | tool_contact_id -> tool_contact_ids

idsolv schema | pattern is missing the property "type"

**Comment by jmfernandez** [comment]
Commits 6a696adcee1af2c38850ea511092d9f3c8b19f21 and 8a7b41d915b8ed286e5a8faf2612db2878c7bc07 should fix the issue
