### ISSUE TITLE
Deposition policy

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#87]
Proposed policy:
1. Community User generates a complete set of Json objects using 1) his/her own ids for new objects 2) Permanent Ids for objects already in the system
2. Community User validates off-line the dataset
     That implies that validator software should have two "modes" accept 1)Free ids or  2)OEB Ids
3. Community User uploads via REST the dataset
     Authentication data is recorded and associated to the upload dataset 
4. Uploader backend generates all required temporary Ids (see #82 ) and update objects
5. Uploader complete the dataset with the necessary  objects (i.e. TestActions)
6. Uploader re-validate with new ids. Dataset is incorporated to dev. DB
7. Details to be defined: Final Ids are generated and dataset moved to oeb

In parallel (see #79 #81 ) ownership data is generated and placed in the appropriate user management data model (to be defined), in collaboration with authentication engine.

**Comment by jmfernandez** [comment]
Unless I'm missing some detail @jlgelpi @redmitry , I consider this issue can be closed, as the different involved software pieces exist, doing more or less the work. If I'm wrong, do not hesitate to reopen it.
