### ISSUE TITLE
Dataset, Datalink types

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#88]
-Not sure which is the meaning of datalink types:
"compressed", "archive", "metalink", "sums" 

-Curie may need to indicate a resolver system

**Comment by jmfernandez** [comment]
The _`attrs`_ array tries to describe the meaning of the URI through the `enum`, but some cases should not happen. I have just pushed a new version (commit df380476fe22e063f327b7e7485cd8e87b238fe9), redoing the _`uri`_ with a `oneOf`construction, so other keys are not valid in the case of embedded JSON data. Also, the documentation has improved a bit.

I'm leaving this issue open, so @javi-gv94 and @jlgelpi can check with their implementations and data the changes' correctness. We can even change the name of the _`uri`_ key to _`data`_ in the case of embedded JSON data

**Comment by javi-gv94** [comment]
I have already tested the new uri feature and works for me.
I attach three examples of how I am currently building the datasets
* [participant](/home/jgarrayo/benchmark_repositories/benchmarking-data-model/prototype-data/1.0.x/TCGA/participant_datasets/Dataset_participant_ACC_2020plus_OEBD002t000003.json)
* [assessment](/home/jgarrayo/benchmark_repositories/benchmarking-data-model/prototype-data/1.0.x/TCGA/assessment_datasets/Dataset_assessment_ACC_2020plus_TPR_OEBD002t00008W.json)
* [challenge](/home/jgarrayo/benchmark_repositories/benchmarking-data-model/prototype-data/1.0.x/TCGA/challenge_datasets/Dataset_Challenge_ACC_2020plus_OEBD002t0000OE.json)

Let me know if that's how we want the datalink

**Comment by jmfernandez** [comment]
Seems good. Looking at them, it is more clear we need a change for the embedded data case, so we do not include unneeded nested structures

**Comment by jmfernandez** [comment]
Now you have used changes from dfa3cad126f5b8d0f0d2ecc1e2b55d399dc9cd72 and 1aabbef3190acb46341a2af87c114f773e357575 , should we close this issue?
