### ISSUE TITLE
Idsolv pattern property

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#89]
Draft-07 permits adding "regex" as the value 
http://json-schema.org/draft-07/json-schema-release-notes.html

**Comment by jlgelpi** [comment]
Not sure to understand this field, is it a pattern on the id? on the Url?

**Comment by jmfernandez** [comment]
JSON Schema Draft-07 has additional default formats for strings. One of them is "regex", which model correct regular expressions. As "pattern" is a regular expression, I have just added it in commit 12582416625eeedc78d9680164e10c91a53d8957
