### ISSUE TITLE
"tool_contact_id" in "Tool"

### ISSUE THREAD

**Issue by diglesia** [inab/benchmarking-data-model#9]
The tool's contact could be an individual or a helpdesk, but the schema of "contact" requires name and surname.  
Proposed solution: To distinguish between contact person and helpdesk in order to determine the required fields.

**Comment by jlgelpi** [comment]
Makes sense. Tools definition should align as much as possible with bio.tools schema (or Dmitry's version of it). I think that they have separated entries.
