### ISSUE TITLE
Community.Metrics_categories.metrics.tool_id to Metrics?

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#91]
Could not this be better placed on the metrics class?

**Comment by jmfernandez** [comment]
I'm afraid it is more complicated than that.

We modelled this case in **`Community`** after @juergenhaas explained us long time ago that, depending on the kind of tool participating in an event, one set or another of instantiated metrics could be applied. A metrics category should explain which specific tool is being used for each metric in that category.

On the other hand, we have in **`Metrics`**, for each metric, the list of potential tools implementing it. Maybe it could be modelled on the **`Tool`** side instead on the **`Metrics`** one, so we can remove the extra reference to **`Metrics`**. If we want to be permissive, we can become it a `oneOf` construction, so we model the cases where it is not registered the **`Tool`** implementing the **`Metrics`**.

As a side effect, I have just realized that we are not using the _`category_id`_ from **`Community`** in any other place.

**Comment by jmfernandez** [comment]
With the changes from e3bc8d0 , 93a43ab and 2400ae6, this issue seems resolved
