### ISSUE TITLE
dataset schema crashes validator

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#92]
The local validator crashes due to the "," found in line 119 of the [dataset schema](https://github.com/inab/benchmarking-data-model/blob/1.0.x/json-schemas/1.0.x/dataset.json).
Related with #88 and df380476fe22e063f327b7e7485cd8e87b238fe9
easy one :)

**Comment by jmfernandez** [comment]
My fault. I have just fixed in 22ae0527a0471a5c93b485f2386992aab928f549 . Thanks for the feedback!
