### ISSUE TITLE
acronym for challenge schema.

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#93]
As we have an acronym field in community schema we should also have a acronym field in the challenge schema ex :  ACC Adrenocortical Carcinorna.

**Comment by jmfernandez** [comment]
Having a look at **`Challenge`** and **`Community`**, the latter has 3 descriptive attributes, _`acronym`_, _`name`_ and _`description`_, meanwhile the former only has _`name`_. Should we add as optional _`acronym`_ and / or _`description`_?

**Comment by jlgelpi** [comment]
Challenges have their orig_id that would correspond to the "acronym", A description is always useful, actually could be of general use.

**Comment by javi-gv94** [comment]
orig_id is usually "bench event orig_id + challenge acronym" (eg: TCGA:2018-04-05_ESCA)
As we need to visualize that acronym in the interface, I think it is worth to have a new property with it, so that we don't need to 'split' the orig id
Description cold also be useful.

**Comment by jlgelpi** [comment]
Ok then.

**Comment by jmfernandez** [comment]
Added _`acronym`_ and _`description`_ optional keys in commit d3657dc48631aac839abaf5abe4cb5dd7e27b160
