### ISSUE TITLE
"visibility" field in Dataset schema

### ISSUE THREAD

**Issue by vsundesha** [inab/benchmarking-data-model#95]
"visibility" is currently set as a non required field in the Dataset schema. I think it should be added as a required field.

**Comment by javi-gv94** [comment]
Following the visibility discussion, I think we need to specify how is the 'mapping' between the different types of datasets and their visibility (or at least define which are the defaults, as a user might decide to change his/her dataset's visibility from 'participant' to 'public', for instance).
Here is a table that summarizes how I see it:

<table style="width:100%" align="center">
  <tr>
    <th>Type</th>
    <th>Visibility</th>
  </tr>
  <tr>
    <td>public reference</td>
    <td>public</td>
  </tr>
  <tr>
    <td>metrics reference</td>
    <td>community</td>
  </tr>
  <tr>
    <td>input</td>
    <td>challenge or public¿?</td>
  </tr>
  <tr>
    <td>participant</td>
    <td>participant</td>
  </tr>
  <tr>
    <td>assessment</td>
    <td>participant</td>
  </tr>
  <tr>
    <td>challenge</td>
    <td>participant</td>
  </tr>
 

</table>
