### ISSUE TITLE
Expand the metrics concept to include other "operations" like visualization, validation, etc. 

### ISSUE THREAD

**Issue by jlgelpi** [inab/benchmarking-data-model#97]
Extend the concept to any operation on a dataset, focussing in the operation itself (definition, container, algorithm, reference). Clear examples are statistic treatments on metircs results, transformations for visualization.

**Comment by jmfernandez** [comment]
Could you develop it further, please?

**Comment by jlgelpi** [comment]
"Metrics" was designed for participantDataset -> AssessmentDataset. After that,  operations making assessmentDS -> StatisticsDS (analysis of results), StatisticsDS -> StatisticsDS (aggregation, summaries, etc) have also methods involved that we currently do not consider explicitly. We can use the "Metrics" data model to include any kind of operations among datasets.

**Comment by jmfernandez** [comment]
Based on what you wrote, as far as I see it, `Metrics` are a subclass of an abstract `Transformation`. In any case, their "instances" are abstract descriptions of transformations / metrics. They are optionally referred from the _`depends_on`_ section in the `Dataset` instances, and the implementation which was used to do it is optionally referred at the same level through a `Tool` id.

So, I agree on renaming Metrics to Transformation, and the names of the facets along the schemas referring these.

**Comment by jmfernandez** [comment]
At the end, we are keeping "Metrics" name, but with the spirit of a "Transformation"
