### ISSUE TITLE
Metrics Visualization

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#98]
Currently, we have not specified which metrics we want to visualize for a specific challenge, and how to visualize them.
For instance, in the case of 2D visualization, we should know which metric is represented in the X axis and which one in Y. 
Should the data model cover this? For instance at the challenge level.

(I am not sure if this is related with #97)

**Comment by javi-gv94** [comment]
Should this be considered in the metricsCategory schema created in e3bc8d02271130cdce0618e90e9dbeb32dc14cd0?
e.g. for TCGA we would have a MetricsCategory 'Precision-vs-recall', which would be linked to a 2D visualization and specify which metric is represented in the X axis and which one in Y.
For communities that have simple results/metrics, we could use a 'generic' metrics category.

**Comment by jmfernandez** [comment]
As this is beyond the data model, but related to their primary users, I guess it is better modeled through the extendable `_metadata` mechanism. I'm leaving this issue open, in order to give it a thought on platform consolidation.

**Comment by jmfernandez** [comment]
Fixed at https://github.com/inab/OEB_level2_data_migration
