### ISSUE TITLE
community_id in Tool and Metrics schemas

### ISSUE THREAD

**Issue by javi-gv94** [inab/benchmarking-data-model#99]
I think we should include community_id in those schemas. It is already in the database but not in this repository.

We are using in cases like: for an assessment dataset, we know the associated tool and metric ids, and we need to search in those collections to get the actual names, which we show in the interface.

**Comment by vsundesha** [comment]
Related to the question, currently in the database the community_id for the Metrics Schema is a String and for the Tool Schema is an Array. I understand that a tool can be part of more than one community but can a metric belong to more than one community?

**Comment by vsundesha** [comment]
```
{ 
    "_id" : "OEBM003000000B", 
    "orig_id" : "QfO:referenceTreeFam-A_recall", 
    "title" : "True Positives Rate for Reference Gene Phylogenies: TreeFam-A", 
    "community_id" : "OEBC003", 
    "metrics_contact_id" : [

    ], 
    "formal_definition" : "TPR = TP / (TP + FN)", 
    "description" : "Agreement (sensitivity) with Reference Gene Phylogenies - TreeFam-A measured through the True Positives Rate (TPR)", 
    "references" : [
        "doi:10.1093/bib/bbr034", 
        "doi:10.1093/nar/gkj118"
    ], 
    "_schema" : "https://www.elixir-europe.org/excelerate/WP2/json-schemas/1.0/Metrics"
}
```
As seen in this example, currently we are considering metrics as community-specific. Should the community_id in the metric schema be a string instead of having an array in the "Implementation" field

**Comment by jmfernandez** [comment]
A community could have more than one implementation, or revisions, of an abstract metric.

**Comment by vsundesha** [comment]
okay, I guess we can close this issue, Thank you !
